EtymoList = {
  'di':['day','diary','meridian','dismal'],  
  'sol':['sun','solar','solstice','parasol','insolate','solarium'],
  'domina':['lady','donna','belladonna','dame','damsel','demoiselle','madenoiselle'],
  'dominus':['master','dominate','predominate','domination','dominator','dominatrix','domineer','domain'],
  'dome':['house','domestic','domesticate','domicile','domatium'],  
  'luna':['moon','lunar','perilune','apolune','lunatic'],
  'luc':['light','luciferous','lucid','lucigen','lucent','noctilucent','translucent','lumen','luminary','luminous','luminance','luminferous','transilluminae','illuminate','illuminant','illumine','luminescence','autoluminescence','bioluminescence'],
  'mas':['male','masculine','male','macho','emasculate'],
  'merc':['trade','commerce','commercial','merchant','merchandise','mercenary','mercy','market'],
  'di':['god','deity','deify','deist','divine'],
  'pater':['father','compatriot','patriarch','patricide','paternoster'],
  'chronos':['time','chronology','anachronism','diachronic','synchronous','asynchronous'],   
  'arctos':['north','Arctic','Antarctic'],
  'aster':['star','astronomy','astrology','astromancy','astronaut','asterisk','asteroid','disaster'],
  'stella':['star','constellation','stellar'],
  'nomos':['law','economy','autonomy','gastronomy'],
  'zoe':['zodiac','zoology','zoo','phanerozoic','paleozoic','mesozoic','cenozoic'],
  'galact':['milk','galaxy'],
  'lact':['milk','lactose'],
  'terra':['earth','Mediterranean','inter','disinter','subterrane','territory'],
  'ge':['earth','geometry','geography','geology'],
  'phot':['light','photograph','photon','photosphere','photogen','photosynthesis','phosphorus'],
  'phobos':['afraid','hydrophobia','acrophobia','panophobia'],
  'io':['wander','ion','ionosphere','ionogen'],
  'ops':['eye','autopsy','myopia','hyperopia','xanthopia','optics','optician'],
  'aqua':['water','aquarium','aqueduct','aquifer','aquacada','aqualung','aquanaut','aquaculture'],
  'medea':['meditation','mathematics'],
  'calos':['beautiful','calligraphy','calisthenics','kaleidoscope'],
  'muse':['art','music','museum'],
  'aoide'['tragedy','comedy','odeon','prosody','threnody','rhapsody','ode'],
  'mneme':['memory','mnemonics','amnesty','amnesia','promnesia'],
  'ment':['mind','mentation','mental','mention','monitor','reminiscence','remember','comment','dementia','remind'],
  'eros':['love','erotic','reotica','eroticism','erotomaniac','erotogenesis','erotology'],
  'uranos':['sky','uranography','uranology','uranometry','uranolite','uranophobia'],
  'choros':['choir','chorister','chorus','choral','carol','chorea','choregraphy'],
  'eu':['good','euthanasia','eulogy','eudemonia','eugenics','euphony','euphemism','euphoria','eukaryote','eucalypytus'],
  'polys':['many','polunomial','polypoly'],
  'melos':['limbs','melody','melisma','melodrama'],
  'hora':['time','hour','horal','horography','horologe','horoscope'],
  'chloros':['green','chlorine','chlorophyll','cholesterol','cholecyst','choleric','choler','chelera'],
  'ver':['spring','primavera','verdure','verdant','vernal','verdigris'],
  'auxo':['grow','auxin','auxiliary','auxesis','auxology','auxocyte','augment','August','auction','author'],
  'carpos':['fruit','excerpt','acarpous'],
  'thesis':['make','hypothesis','synthesis','photosynthesis','theme','thematic','theme','thematic'],
  'poeo':['make','poem','pathopoiesis','poet'],
  'eirene':['peace','irenic','irenicon'],
  'carus':['care','caress','charity','cherish'],
  'carta':['card','cartoon','carte','chart','charter','cartel','uncharted'],
  'carrus':['car','cargo','carriage','carry','career','chariot','charge','surcharge','discharge'],
  'calx':['stone','chalk','calcium','calcify','calcimine','calculus','calculate'],
  'caput':['head','caput','captain','chief','cape','cabbage','bieceps','triceps','decapitate','capital'],
  'phren':['mind','phrenic','phrenetic','frantic','schizophrenia'],
  'pant':['all','Pandora','panacea','pancreas','panorama','panoply'],
  'theos':['god','theology','atheism','thoecracy'],
  'cyclos':['circle','cycle','bicycle','tricycle','unicycle','recycle','tetrecycline','cyclamen','cyclone'],
  'hecaton':['hundred','hectare','hecatomb'],
  'centum':['hundred','century','percent','centipede'],
  'potamos':['river','hippopotamus','potamology','Mesopotamia'],
  'tineo':['hold','continent'],
  'helios':['sun','helianthus','heliocentric','perihelion','aphelion','helium','heliosis','heliotherapy','heliozoa','heliolatry'],
  'selene':['moon','selenium','selenology','selenodesy','selenodont'],
  'mene':['moon','semester','trimester','mensis','menstruation','amenia','menostasia'],
  'hyper':['over','hyperactive','hypertension','hypertext','hypersensitive','hyperopia'],
  'pro':['before','problem','Procyon','prophet','provoke','propose','proceed','proclaim','produce','profess','program','progress','promise','promote','propel','prostate','protract','prospect','ptotect'],
  'epi':['upon','epidemic','epicenter','epidermis','epigram','epiphyte'],
  'dora':['donate','donor','donee','pardon','condone'],
  'tlenai':['bear','extol','talent','thole','tolerance'],
  'cartos':['manage','democracy','aristocracy','bureaucracy','hierocracy','theocracy','plutocracy','nomocracy','gerontocracy'],
  'lethe':['forget','lethargy','lethal'],
  'caio':['burn','causalgia','encaustic','atmocausis','casustic']
  'phaos':['light','phenomenon','phantasm','phantom','fantasy','fancy','phanerosis','phenol','fenestra','phase','phosphorus'],
  'rheo':['river','rheology','logorrhea','rheum'],
  'rivus':['rivulet','rival','derive'],
  'servo':['save','conserve','consevator','conservative','observe','obsevatory','preserve','preservation','reserve','reservoir'],
  'juvenis':['young','juvenile'],
  'moneo':['remind','monitor','monument','admonish','summon','money'],
  'curr':['run','cursory','cursive','cursor','precursor','courser','course','concourse','discourse','recourse','curriculum','corsair','current','courier','corridor','occur','recur','concur'],
  'mater':['mother','maternal','matriarch','matricide','maronymic','matron','matrimony','alma mater','metropolitan','metro','material','matter','matrix','metralgia'],
  'cre':['grow','crescent','decreascent,','increase','decrease','recruit'],
  'eido':['see','eidos','eidolon','idol','idolatry','kaleidoscopic','idea'],
  'vid':['see','video','evidence','providence','invidious','vide','vision','visual','visible','ivisible','visage','previse','visit','advise','revise','revision','provide','supervise','deivise','view','preview','review','interview','survey','envy'],
  'sede':['seat','sit','preside','president','reside','resident','settle','insidious','assiduous',',sedentary','sedate','dissident','supersede','sederunt','sediment','assess','catherdral'],
  'gigas':['giant','gigantic','gigantocyte','gigantosoma','giant'],
  'urina':['urine','urine','urenthra','urinal','urea','uremia','anuria','oliguria','diuretic','proteinuria','pyuria','urinate','ureter','enuresis'],
  'ouros':['mount','orogeny','orography','orometer','oregano'],
  'chaos':['chaos','chaotic','chasm'],
  'nyct':['night','nyctalopia','nycturia','nyctophobia','nyctanthes'],
  'nataos':['swim','natant','natatorium'],
  'thauma':['scene','thaumatrope','thaumaturge'],
  'thea':['see','theater','theory'],
  'geront':['old','gerontal','progeria','gerocomium','agerasia','gerocomy','geratology','geriatrician','gerodontics','gerontocracy','gerontophile'],
  'granum':['grain','granadilla','granulose','granary','grange','pomegranate','garnet','grenade','grantie'],
  'sthenos':['power','sthenia','asthenia','amyosthenia','amyosthenia','asthenopia','cardiasthenia','neurasthenia','calisthenics'],
  'hal':['sea','halite','halogen','halbios','halophile','halophyte','haline'],
  'salum':['sea','salt','salary','peninsula','isolate','insulin','isle','islet','saleratus','saliferous','salify','salami','sauce','sausage','salad','saline','saltcellar','saltery'],
  'orthos':['true','Orthodox','orthography','orthodontics','orthopaedics'],
  'hydor':['water','hydrophobia','hydrangea','hydrogen','hydrargrum','hydrant','hydrocephalus','hydrofoil','hydrobiont','hydrodynamics','hydrolysis'],
  'cheima':['winter','cheimaphobia','Chimaphila','isocheim','Himalayas'],
  'leo':['lion','leopard','chameleon','dandelion'],
  'niht':['night','nightmare','midnnight','tonight','Nightingale','nightshade','nightclub'],
  'hemera':['day','Decameron','ephemeron','Hemerocallis','hemeralopia'],
  'thanatos':['death','cacothanasia','cacography','cacophony','euthanasia','hydrothanasia','electrothanasia','thanatoid','thanatopsis','thanatorium','athanasia'],
  'hypnos':['sleep','hypnosis','hypnotherapy','hypnopedia','hypnotic','hypnagogic','euhypnia','dyshypnia','hypnology','hypnophobia'],
  'somnus':['sleep','somnanbulance','somnolent','somnifacient','somniferous','somniloquence','somniloquy','insomnia'],
  'oneiros':['dream','oneiric','oneirocrite','oneirocritic','oneironmancy'],
  'porpheus':['dream','morphine','morphinomania'],
  'morphe':['shape','morphosis','anamorphosis','metamorphosis','morphology','geomorph','polymorphic','isomorphic'],
  'moira':['share','merit','emeritus','demerit','isomer','polymer'],
  'tropos':['turn','atropa','Atropine','tropic','subtropic','troposphere','apotropaion','heliotrope','geotropism','phototropism','entropy'],
  'phileo':['love','philosophy','philharmonic','neophilia','philanthropy','zoophilous','bibliophilist','Philomel'],
  'pomos':['work','geoponics','hydroponics','aeroponics'],
  'limos':['hungry','limosis','bulimia'],
  'algia':['pain','algesthesis','alganesthesia','Analgin','cardialgia','cephalagia','cervicalgia','gastralgia','dentalgia','orchidalagia','nostalgia'],
  'pseides':['false','pseudoscience','pseudopos','psedudacusis','pseudodox','pseudologia','pseudonym'],
  'logos':['words','philoloy','eulogy','apology','monlogue','prologue','epilogue','dialogue'],
  'amphi':['two','amphibian','amphiphyte','amphitheater'],
  'dys':['bad','dysfunction','dyslexia','dyspepsia','dystopia'],
  'sophos':['wisdom','philosophy','sophomore'],
  'axon':['wheel','axis','axle','axilla'],
  'nebula':['cloud','nebula','nebulous','nebulizer','nimbus'],
  'cupid':['want','cupidity','concupiscence','covet'],
  'psyche':['mind','psychology','psychiatry','psychopathy','psychoanalysis','psychoneurosis','psychedelic','psychism','psychogenesis','psychosis','psycho'],
  


  


  


  












}
